config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  namespace :owners do
    resources :tractors, only: [:index]
    resources :bookings, only: [:index] do
      member do
        patch 'accept'
        patch 'refuse'
      end
    end
  end

  resources :bookings, only: [:index]

  resources :tractors, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tractor
end

app/models/tractor.rb
class Tractor < ApplicationRecord
  has_one_attached :photo
  has_many :bookings
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :tractors, dependent: :destroy
  has_one_attached :avatar
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.tractor = Tractor.find(params[:tractor_id])
    @booking.total_price = ((@booking.ending_date - @booking.starting_date).to_i * @booking.tractor.price_per_day)
    @booking.save!
    redirect_to bookings_path
  end


private

  def booking_params
    params.require(:booking).permit(:status, :total_price, :starting_date, :ending_date, :tractor_id, :user_id)
  end
end

app/controllers/owners/bookings_controller.rb
class Owners::BookingsController < ApplicationController
    before_action :find_booking, only: [:accept, :refuse]

  def index
    # @bookings = []
    # current_user.tractors.each do |tractor|
    #   @bookings << tractor.bookings
    # end
    # @bookings.flatten!


    @bookings = Booking.includes(tractor: :user).where(tractors: { user: current_user })
  end

  def accept
    @booking.status = 'true'
    @booking.save
    redirect_to owners_bookings_path

  end

  def refuse
    @booking.status = 'false'
    @booking.save
    redirect_to owners_bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/owners/tractors_controller.rb
class Owners::TractorsController < ApplicationController

  def index
    @tractors = current_user.tractors
  end

  private

  def tractor_params
    params.require(:tractor).permit(:photo, :title, :descritpion, :price_per_day)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/tractors_controller.rb
class TractorsController < ApplicationController

  def index
    @tractors = Tractor.geocoded


    @markers = @tractors.map do |tractor|
      {
        lat: tractor.latitude,
        lng: tractor.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { tractor: tractor }),
        image_url: helpers.asset_url('feuille.png')
      }
    end
  end

  def show
    @tractor = Tractor.find(params[:id])
    @booking = Booking.new
  end

  def new
    @tractor = Tractor.new
  end

  def create
    @tractor = Tractor.new(tractor_params)
    if @tractor.save
      redirect_to tractor_path(@tractor)
    else
      render :new
    end
  end

  private

  def tractor_params
    params.require(:tractor).permit(:photo, :title, :descritpion, :price_per_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tractor_photo_path(tractor)
    tractor.photo.attached? ? cl_image_path(tractor.photo.key, height: 300, width: 400, crop: :fill) :  image_path('default-tractor.png')
  end
end

app/views/bookings/_form.html.erb
<div class="container">
  <div class="form-wrapper">
    <%= simple_form_for [@tractor, @booking], method: "post" do |f| %>
      <%= f.input :starting_date, as: :string, required: false, input_html: {id: "range_start"} %>
      <%= f.input :ending_date, as: :string, required: false, input_html: {id: "range_end"} %>
      <%= f.button :submit, "Book Now", class: "btn btn-form" %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="d-flex justify-content-center user-booking-container">
  <% @bookings.each do |booking|  %>
    <div class="my-loc d-flex p-2 m-3 shadow-sm rounded align-middle">
      <%= link_to booking.tractor, class: "booking-link" do  %>
        <%= cl_image_tag booking.tractor.photo.key, height: 200, width: 200, crop: :fill  %>
      <% end %>
      <div class="booking-info d-flex">
        <div class="description-booking">
          <h4> <%= booking.tractor.title %></h4>
        </div>
        <div class="d-flex details-rental justify-content-between">
          <div class="duration-date">
            <p>From <%= booking.starting_date.strftime("%d.%m.%Y")  %>
              <i class="fas fa-chevron-circle-right ml-2"></i>
              <i class="fas fa-chevron-circle-right mr-2"></i>
              <%= booking.ending_date.strftime("%d.%m.%Y")  %>
            </p>
          </div>
          <div class="price-statut-rental d-flex justify-content-between">
            <div class="rental-statut d-flex align-items-center">
              <% case booking.status
                  when "Accept"%><i class="far fa-check-square color-green"></i>
                <%when "Refuse"%><i class="far fa-times-circle color-red"></i>
                <%when "pending"%><div class="text-pending"><h5>Pending</h5></div><span> </span><div class="bounceball"></div>
              <% end %>
            </div>
            <div class="total-rental-price">
              <p>Total<br><%= booking.total_price%>€</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Vroom::BnB</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!--Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/fond' %>
  <%= yield %>
  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= yield(:after_application_pack) %>
</body>
</html>

app/views/owners/bookings/index.html.erb
<!-- OWNER INDEX OF ALL BOOKING  -->



<div class="index-bookings-body">
    <div class="container">
      <div class="d-flex justify-content-center">
        <div class="history w-100">
          <% @bookings.each do |booking| %>
            <div class="my-locs m-2 shadow-sm rounded d-flex align-middle mt-3">

              <div class="container">
                <div class="row d-flex align-items-center justify-content-between">

                  <div class="col-md-auto d-flex p-2">
                    <%= cl_image_tag booking.user.avatar.key, width: 60, height: 60, crop: :fill, class: 'rounded-circle align-self-center' %>
                  </div>

                  <div class="col-md-2 ">
                    <%= booking.user.firstname %>
                    <%= booking.user.lastname %>
                  </div>


                  <div class="col-md-auto d-flex border-left ">
                    <%= cl_image_tag booking.tractor.photo.key, width: 60, height: 60, crop: :fill, class: 'rounded-circle' %>
                  </div>

                  <div class="col d-flex ">
                    <%= booking.tractor.title %> <%= booking.starting_date %> to <%= booking.ending_date %>
                  </div>





                  <div class="col col-md-2">
                    <div class="text-center ">
                      <% if booking.status == 'true' %>
                        <h3><span class="status"><i class="fas fa-check"></i> Accepted</span></h3>
                      <% elsif booking.status == 'false' %>
                        <h3><span class="status"><i class="fas fa-times"></i> Refused</span></h3>
                      <% else %>
                        <%= link_to "Accept", accept_owners_booking_path(booking), method: 'patch', class: 'btn btn-success btn-sm' %>
                        <%= link_to "Refuse", refuse_owners_booking_path(booking), method: 'patch', class: 'btn btn-danger btn-sm'  %>
                      <% end %>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/owners/tractors/index.html.erb
<div class="d-flex justify-content-center user-booking-container">
  <% @tractors.each do |tractor|  %>
  <div class="my-loc d-flex p-2 m-3 shadow-sm rounded align-middle">
    <%= link_to tractor, class: "booking-link" do  %>
    <%= cl_image_tag tractor.photo.key, height: 200, width: 200, crop: :fill  %>
    <% end %>
    <div class="booking-info px-2">
      <div class="description-booking">
        <h4> <%= tractor.title %></h4>
      </div>
      <div class="price-statut-rental d-flex justify-content-between">
        <div class="rental-statut pt-3 px-2 align-items-center">
         <div class="leaf-icon d-flex">
          <p class="px-2">Efficacity</p>
          <% case tractor.speed
            when 1 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf "></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
            <% when 2 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active "></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
            <% when 3 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
            <% when 4 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i></p>
            <% when 5 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i></p>
            <% end %>
          </div>
          <div class="pump-icon d-flex ">
            <p class="px-2">Consumption</p>

            <% case tractor.consumption
              when 1 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
              <% when 2 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active "></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
              <% when 3 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
              <% when 4 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i></p>
              <% when 5 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i></p>
              <% end %>
            </div>
          </div>
          <div class="total-rental-price px-2">
            <p>Price<br><%= tractor.price_per_day%>€</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<%= content_for(:after_application_pack) do %>
  <%= javascript_pack_tag 'home' %>
<% end %>

<div class="home-body">

  <div class="container">
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2">
      <div class="col">
        <div class="shadow-sm rounded p-3 mt-5">
          <h3 class="text-center mb-3">Make a team with one of our Mowing-tractor</h3>
          <p class="text-justify mx-3">Find a tractor adapted at what you need, whatever your situation you can find the perfect tractor to maintain the turf. <br>It's the perfect way to have a beautiful lawn, without mecanic problems and for a good price.</p>
        </div>
      </div>
      <div class="col">
        <div class="shadow rounded my-5">
          <div class="images rounded" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(<%= image_path "map.png" %>);"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row row-cols-1">
      <div class="col">
        <div class="cta d-flex justify-content-center p-5">
          <%= link_to 'See all our Mowing-Tractors!', tractors_path, class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2">

      <div class="col">
        <div class="shadow rounded mb-5">
          <div class="images rounded" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "home-young-woman.jpg" %>);"></div>
        </div>
      </div>

      <div class="col">
        <div class="shadow-sm rounded p-3">
          <h3 class="text-center mb-3">Find a machin close to your garden</h3>
          <p class="text-justify mx-3">When you're in a bind, or need an mowing machine quickly, request us for rental equipment. We supply well maintained mowing agricultural equipment, mowers specialized equipment to Nantes area. </p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.8)), url(https://s3-eu-west-1.amazonaws.com/sc-files.pjms.fr/p/pjms/804/000/396/978/62539300c6d243a78b669560b49f98a0.jpg);">
  <div class="container">
    <h1>Bring the perfect <strong>mowing tractor</strong> to your door!</h1>
    <p>Let's find the perfect machine for your grass!</p>
    <%= link_to 'Find yours!', tractors_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/shared/_fond.html.erb
<div class="fond-container">
    <div class="feuille-h"></div>
    <div class="feuille-b"></div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> in my mowing garden!
  </div>
</div>

app/views/shared/_navbar.html.erb
<% navbar_bg_class = params[:controller] == 'pages' && params[:action] == 'home' ? '' : 'bg-light'  %>
<% navbar_text_class = params[:controller] == 'pages' && params[:action] == 'home' ? 'text-light' : 'text-success'  %>

<div id="nav" class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= navbar_bg_class %> ">
  <div class="d-flex justify-content-start">
    <%= link_to root_path,  class: "navbar-brand" do %>
      <%= image_tag "https://www.nicepng.com/png/full/119-1198588_grass-fed-standards-grass-icon-vector-png.png" %>
    <% end %>
    <h1 class="target mt-3 <%= navbar_text_class %>">vroom::BnB</h1>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All our tractors", tractors_path, class: "target nav-link #{navbar_text_class}" %>
        </li>
        <li class="nav-item">
          <%= link_to "My rentals", bookings_path, class: "target nav-link #{navbar_text_class}" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, crop: :scale, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "unnamed.png", class: "nopic avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My ads", owners_bookings_path, class: "dropdown-item" %>
            <%= link_to "My tractors", owners_tractors_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link #{navbar_text_class}" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tractors/_info_window.html.erb
  <%= link_to tractor do  %>
    <div class="info-container rounded">
      <div class="d-flex flex-column justify-content-between align-items-center">
        <%= cl_image_tag tractor.photo.key, width: 60, height: 60, crop: :fill, class: 'rounded-circle' %>
        <h6><%= tractor.title %></h6>
        <p class="price-map"> <%= tractor.price_per_day %>€</p>
      </div>
    </div>
  <% end %>

app/views/tractors/index.html.erb
<div class="index-body">
  <h1 class='pt-5 text-center border-bottom'>All tractors</h1>
  <div class="container">
    <div class="row px-5">


      <!-- START --  TRACTORS -- COLUMN -->
      <div class="col-8">
        <div class="row">
          <% @tractors.each do |tractor| %>
          <div class="col-12 col-sm-6 col-md-6">
            <div class="rounded">
              <%= link_to tractor do  %>
              <div class="card mt-5">
                <div class="image-cards" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.5)), url('<%= tractor_photo_path(tractor) %>')">
                  <div class="title">
                    <h1> <%= tractor.title %></h1>
                  </div>
                  <div class="price">
                    <h2><%= tractor.price_per_day %>€</h2>
                  </div>
                  <div class="info">
                    <!-- START --  TRACTORS -- DESCRIPTION -->
                    <div class="description">
                      <h3><%= tractor.description %></h3>
                      <% case tractor.consumption
                       when 1 %><p>Consumption : <i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
                       <% when 2 %><p>Consumption : <i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump "></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
                       <% when 3 %><p>Consumption : <i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
                       <% when 4 %><p>Consumption : <i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i></p>
                       <% when 5 %><p>Consumption : <i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i></p>
                       <% end %>
                       <% case tractor.speed
                         when 1 %><p>Efficacity : <i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
                         <% when 2 %><p>Efficacity : <i class="fas fa-leaf active"></i><i class="fas fa-leaf "></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
                         <% when 3 %><p>Efficacity : <i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
                         <% when 4 %><p>Efficacity : <i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i></p>
                         <% when 5 %><p>Efficacity : <i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i></p>
                         <% end %>
                    </div>
                    <!-- END --  TRACTORS -- DESCRIPTION -->
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <!-- END --  TRACTORS -- COLUMN -->

      <!-- START -- MAP -- COLUMN -->
      <div class="col-12 col-sm-4 col-md-4">
        <div class="map-container">
        <div class="mt-5 d-flex justify-content-center">
          <div
          class="rounded shadow-sm"
          id="map"
          style="width: 100%;
          height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
        </div>
      </div>
      <!-- END -- MAP -- COLUMN -->

    </div>
  </div>
</div>

app/views/tractors/new.html.erb
<h1>Add new tractor</h1>
  <%= simple_form_for @tractor do |f| %>
  <%= f.input :title %>
  <%= f.input :photo, as: :file %>
  <%= f.input :description %>
  <%= f.input :price_per_day %>
  <%= f.submit %>
<% end %>

app/views/tractors/show.html.erb
<div class="show-body">
  <div class="container">
  <%= link_to "Back", tractors_path, class: "btn btn-outline-success btn-back" %>
    <div class="all-show shadow-sm my-3">
      <div class="top-show d-flex justify-content-between">
        <h2><%=@tractor.title  %></h2>
        <h5 class=""><%= @tractor.price_per_day %> € /day</h5>
      </div>
      <div class="middle-show">
        <div class="d-flex border-top border-bottom align-items-center">
          <div class="picture-tractor mr-auto">
            <%= cl_image_tag @tractor.photo.key, width: 400,  crop: :fill, class: 'show-tractor-image'%>
          </div>
          <div class="booking-form mr-auto">
            <%= render 'bookings/form' %>
          </div>
        </div>
      </div>
        <div class="bottom-show d-flex justify-content-between p-3">
          <div>
            <p class="px-2"><%= @tractor.description %></p>
              <div class="icons-show">
                <div class="aera-icons d-flex">
                  <p class="pr-3">Aera/hour</p>
                    <div class="leaf-icon">
                      <% case @tractor.speed
                        when 1 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf "></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
                        <% when 2 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active "></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
                        <% when 3 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i></p>
                        <% when 4 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf"></i></p>
                        <% when 5 %><p><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i><i class="fas fa-leaf active"></i></p>
                      <% end %>
                    </div>
                  </div>
                  <div class="consumption-icons d-flex">
                    <p class="pr-3 ">Consumption</p>
                    <div class="pump-icon px-2 ">
                      <% case @tractor.consumption
                        when 1 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
                        <% when 2 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active "></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
                        <% when 3 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i><i class="fas fa-gas-pump"></i></p>
                        <% when 4 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump"></i></p>
                        <% when 5 %><p><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i><i class="fas fa-gas-pump active"></i></p>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="avatar-owner p-2">
                <div class="">
                  <%= cl_image_tag @tractor.user.avatar.key, height: 50, width: 50, crop: :fill, class: 'image-owner rounded-circle' %>
                </div>
                  <div class="owner-first-name pt-2">
                    <%= @tractor.user.firstname %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>